### ISSUE TITLE
Could be a good example for docs.apollostack.com

### ISSUE THREAD

**Issue by helfer** [abhiaiyer91/sample-graphql-meteor-server#1]
Hey Abhi, if you have time to add a SQL part to it (for example for views), this could be a great example app for us to link to here: http://docs.apollostack.com/#Example-apps

**Comment by abhiaiyer91** [comment]
@helfer I added the Sequelize part to the example, but used MySQL instead of sqlite. Just for kicks. I think this could be a great example of plugging in tons of data sources displaying the same types of info. In my latest changes i changed the queries to be clear, "mongoAuthor" vs "sqlAuthor".

**Comment by helfer** [comment]
Looks good! Can you merge this https://github.com/abhiaiyer91/sample-graphql-meteor-server/pull/2
and then make a PR against the docs to include it in the [examples](http://docs.apollostack.com/#Example-apps)?

**Comment by abhiaiyer91** [comment]
Sure will do
