### ISSUE TITLE
result in App.js is undefined 

### ISSUE THREAD

**Issue by morfarpeter** [abhiaiyer91/sample-graphql-meteor-server#4]
Don't know why exactly, but if I log result in App.js's App component i get undefined. If i log postsData, I get and object with mongoPosts and sqlPosts.

```
function App({ postsData }) {
  const { result } = postsData;

    console.log(result, postsData)
```

Am I doing something wrong, or is a newer version of Apollo fetching in a different way or something? :) 

/Peter

**Comment by abhiaiyer91** [comment]
Ah yes. React Apollo changed the way it grabs data. There is no `result` keyword. Do you mind submitting a PR to fix this issue? Thank you!

**Comment by morfarpeter** [comment]
Ah okay... Sure thing. I'll try to have a PR submitted soon :)

**Comment by morfarpeter** [comment]
#5 Done :)
